kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
  labels:
    app: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydeployment
  template:
    metadata:
      labels:
        app:  mydeployment
    spec:
      containers:
        - name: mycontainer
          image: skumarjira/petshopimg
          ports:
            - containerPort: 8080