kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
  labels:
    app: petshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petshop
  template:
    metadata:
      labels:
        app:  petshop
    spec:
      containers:
        - name: mycontainer1
          image: skumarjira/petshopimg
          ports:
            - containerPort: 8080